### ISSUE TITLE
Don't need `node` for `bats`

### ISSUE THREAD

**Issue by glennj** [exercism/bash#544]
We get automated PRs like #543 

The GitHub Actions pull in bats-core with `npm install -g bats`. The Ubuntu package `bats` is bats-core v1.1.0, so we no longer need node for bats.

The job step for CI and PR workflows
```yaml
      - uses: actions/setup-node@v2.4.0
      - name: Install bats-core
        run: sudo npm install -g bats
```
can be changed to
```yaml
      - name: Install bats-core
        run: |
          sudo apt-get update && sudo apt-get -y install bats
```
